DeveloperTeamInsights/Models/Developer.cs
using System.ComponentModel.DataAnnotations;

namespace DeveloperTeamInsights.Models;

public class Developer
{
    public int Id { get; set; }
    public string? DeveloperName { get; set; }
    public int NumberTasksWorked { get; set; }
    public int NumberActivePRs { get; set; }
    public int NumberReviewsConducted { get; set; }
    public int NumberDocumentsGenerated { get; set; }
    public int NumberDocumentsReviewed { get; set; }
    
}

DeveloperTeamInsights/Models/ErrorViewModel.cs
namespace DeveloperTeamInsights.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

DeveloperTeamInsights/Controllers/DeveloperInsightsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DeveloperTeamInsights.Data;
using DeveloperTeamInsights.Models;

namespace DeveloperTeamInsights.Controllers
{
    public class DeveloperInsightsController : Controller
    {
        private readonly DeveloperTeamInsightsContext _context;

        public DeveloperInsightsController(DeveloperTeamInsightsContext context)
        {
            _context = context;
        }

        // GET: DeveloperInsights
        public async Task<IActionResult> Index()
        {
            return View(await _context.Developers.ToListAsync());
        }

        // GET: DeveloperInsights/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var developer = await _context.Developers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (developer == null)
            {
                return NotFound();
            }

            return View(developer);
        }

        // GET: DeveloperInsights/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DeveloperInsights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DeveloperName,NumberTasksWorked,NumberActivePRs,NumberReviewsConducted,NumberDocumentsGenerated,NumberDocumentsReviewed")] Developer developer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(developer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(developer);
        }

        // GET: DeveloperInsights/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var developer = await _context.Developers.FindAsync(id);
            if (developer == null)
            {
                return NotFound();
            }
            return View(developer);
        }

        // POST: DeveloperInsights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DeveloperName,NumberTasksWorked,NumberActivePRs,NumberReviewsConducted,NumberDocumentsGenerated,NumberDocumentsReviewed")] Developer developer)
        {
            if (id != developer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(developer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeveloperExists(developer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(developer);
        }

        // GET: DeveloperInsights/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var developer = await _context.Developers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (developer == null)
            {
                return NotFound();
            }

            return View(developer);
        }

        // POST: DeveloperInsights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var developer = await _context.Developers.FindAsync(id);
            if (developer != null)
            {
                _context.Developers.Remove(developer);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DeveloperExists(int id)
        {
            return _context.Developers.Any(e => e.Id == id);
        }
    }
}

DeveloperTeamInsights/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DeveloperTeamInsights.Models;

namespace DeveloperTeamInsights.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

DeveloperTeamInsights/Views/DeveloperInsights/Create.cshtml
@model DeveloperTeamInsights.Models.Developer

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Developer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DeveloperName" class="control-label"></label>
                <input asp-for="DeveloperName" class="form-control" />
                <span asp-validation-for="DeveloperName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberTasksWorked" class="control-label"></label>
                <input asp-for="NumberTasksWorked" class="form-control" />
                <span asp-validation-for="NumberTasksWorked" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberActivePRs" class="control-label"></label>
                <input asp-for="NumberActivePRs" class="form-control" />
                <span asp-validation-for="NumberActivePRs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberReviewsConducted" class="control-label"></label>
                <input asp-for="NumberReviewsConducted" class="form-control" />
                <span asp-validation-for="NumberReviewsConducted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberDocumentsGenerated" class="control-label"></label>
                <input asp-for="NumberDocumentsGenerated" class="form-control" />
                <span asp-validation-for="NumberDocumentsGenerated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberDocumentsReviewed" class="control-label"></label>
                <input asp-for="NumberDocumentsReviewed" class="form-control" />
                <span asp-validation-for="NumberDocumentsReviewed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DeveloperTeamInsights/Views/DeveloperInsights/Delete.cshtml
@model DeveloperTeamInsights.Models.Developer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Developer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeveloperName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeveloperName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberTasksWorked)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberTasksWorked)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberActivePRs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberActivePRs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberReviewsConducted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberReviewsConducted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberDocumentsGenerated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberDocumentsGenerated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberDocumentsReviewed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberDocumentsReviewed)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DeveloperTeamInsights/Views/DeveloperInsights/Details.cshtml
@model DeveloperTeamInsights.Models.Developer

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Developer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeveloperName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeveloperName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberTasksWorked)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberTasksWorked)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberActivePRs)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberActivePRs)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberReviewsConducted)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberReviewsConducted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberDocumentsGenerated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberDocumentsGenerated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumberDocumentsReviewed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumberDocumentsReviewed)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DeveloperTeamInsights/Views/DeveloperInsights/Edit.cshtml
@model DeveloperTeamInsights.Models.Developer

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Developer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DeveloperName" class="control-label"></label>
                <input asp-for="DeveloperName" class="form-control" />
                <span asp-validation-for="DeveloperName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberTasksWorked" class="control-label"></label>
                <input asp-for="NumberTasksWorked" class="form-control" />
                <span asp-validation-for="NumberTasksWorked" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberActivePRs" class="control-label"></label>
                <input asp-for="NumberActivePRs" class="form-control" />
                <span asp-validation-for="NumberActivePRs" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberReviewsConducted" class="control-label"></label>
                <input asp-for="NumberReviewsConducted" class="form-control" />
                <span asp-validation-for="NumberReviewsConducted" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberDocumentsGenerated" class="control-label"></label>
                <input asp-for="NumberDocumentsGenerated" class="form-control" />
                <span asp-validation-for="NumberDocumentsGenerated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberDocumentsReviewed" class="control-label"></label>
                <input asp-for="NumberDocumentsReviewed" class="form-control" />
                <span asp-validation-for="NumberDocumentsReviewed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DeveloperTeamInsights/Views/DeveloperInsights/Index.cshtml
@model IEnumerable<DeveloperTeamInsights.Models.Developer>

@{
    ViewData["Title"] = "Index";
}

<h1>Index of Developers</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<h2>Developers Insights</h2>

<div class="card-container">
    @foreach (var item in Model) {
        <div class="card">
            <h5>@Html.DisplayFor(modelItem => item.DeveloperName)</h5>
            <p>Developer's work so far in the sprint</p>
            <div class="canvas-container">
                <canvas id="chart-@item.Id"></canvas>
            </div>
        </div>
    }
</div>

@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            @foreach (var item in Model)
            {
                <text>
                    var ctx = document.getElementById('chart-@item.Id').getContext('2d');
                    var chart = new Chart(ctx, {
                        type: 'bar', // Change to 'doughnut' for a donut chart
                        data: {
                            labels: ['Tasks Worked', 'Active PRs', 'Peer Reviews Conducted'],
                            datasets: [{
                                label: 'Developer Activity',
                                data: [@item.NumberTasksWorked, @item.NumberActivePRs, @item.NumberReviewsConducted],
                                backgroundColor: [
                                    'rgba(255, 99, 132, 0.2)',
                                    'rgba(54, 162, 235, 0.2)',
                                    'rgba(255, 206, 86, 0.2)'
                                ],
                                borderColor: [
                                    'rgba(255, 99, 132, 1)',
                                    'rgba(54, 162, 235, 1)',
                                    'rgba(255, 206, 86, 1)'
                                ],
                                borderWidth: 1
                            }]
                        },
                        options: {
                            scales: {
                                y: {
                                    beginAtZero: true
                                }
                            }
                        }
                    });
                </text>
            }
        })
    </script>
}

@* <table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DeveloperName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberTasksWorked)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberActivePRs)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberReviewsConducted)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberDocumentsGenerated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumberDocumentsReviewed)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DeveloperName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberTasksWorked)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberActivePRs)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberReviewsConducted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberDocumentsGenerated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumberDocumentsReviewed)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table> *@

DeveloperTeamInsights/Views/DeveloperInsights/Weekly.cshtml
@{
    ViewData["Title"] = "Weekly Activity";
}

<h2>Weekly Activity</h2>

<ul>
    @for (int i = 0; i < (int)ViewData["NumPRs"]!; i++)
    {
        <li>@ViewData["Message"]</li>
    }
</ul>

DeveloperTeamInsights/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Developer Insights";
}

<div class="text-start">
    <h1 class="display-4">Developer Insights</h1>
</div>

DeveloperTeamInsights/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Developer Team Insights</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DeveloperTeamInsights.styles.css" asp-append-version="true" />
    @* You will need to do a local install for this to work properly. Follow instructions here: https://www.chartjs.org/docs/latest/getting-started/installation.html *@
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="DeveloperInsights" asp-action="Index">Developer Team Insights</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DeveloperInsights" asp-action="Index">DeveloperInsights</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Developer Team Insights - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>